### PR TITLE
25 interactiv cofig command

### PR DESCRIPTION
**Pull request by LeeLux**
irgendwas ist falsch! nicht mergen!

### CODE REVIEW

**Review by Jon-Kle — CHANGES_REQUESTED** [review]
### **First of, the reasons why it didn't run:**

Actually only two:
- In the config.json file, the port was converted into a string
- You used config.save() which removes the values that belong in the dat.json from config.data, and when the program closes, it calls this method again and writes the now empty values into the dat.json file => the values get lost

I changed back the port to a number and commented out the call of config.save() Now it runs without bit issues.  
The dat.json file is changed to the new values, so just pull the .secret file and decrypt it, when you need the file restored.

### **Secondly, what you should change:**

This code is working now for the very most part. There are some details in the appearance that i would like to be different:

- The fourth option doesn't show up correctly. I don't know, why this is, but if you use `print()` instead of `input()` and then print the prompt with `input()`, it should work.
- in the match case section, you wrote `3` twice, so `4`doesn't work.
- For the choices, you write:
```
1. Choice A
2. Choice B
```
This is a bit confusing, so maybe try
```
1 => Choice A
2 => Choice B
```
- If you choose an option it prints the next text directly below the last prompt. This makes it a bit hard to read so maybe add one more newline.

These are the only problems that appear in the foreground.
But in the background as you said it yourself, the code is HUGE...  
There is a coding principle i learned only a few months ago and that is: 
> Write DRY code

DRY means `Don't Repeat Yourself`.  
In your code, you define an internal function for every option and fill them with every option manually.  
This is called `WET` (Write every time) and has some major drawbacks. For example, it is hard to maintain and often not reusable. Maybe you want to read about this for yourself.

I really hope, you take this as a challenge and not as personal criticism:  
I want you to try it again.  
I know, you invested much time in this, but in the end, it will be worth it.

### **Some tips:**

-  use for-loops to print out the options automatically.  
This will make the code more flexible, if there are future changes to the structure of the .json files.
- Don't use too many internal functions. It is a very nice feature, but sometimes the code can be hard to understand if there are too many.
- watch out for the data types of the json file. Some are numbers, some strings. For example you could save the datatype as a variable and use this later to convert the new value to its original type.
- use the python naming convention for functions. Use `_` between the words.

I hope you are okay with this, i am optimistic that you will manage this.  
I wish you good success, have fun!

**Comment by LeeLux** [comment]
I will do that. It will just take some time.

**Comment by Jon-Kle** [comment]
> I will do that. It will just take some time.

Thats no problem, i am glad you are open to this.

**Comment by Jon-Kle** [comment]
Is this ready for review?

**Comment by LeeLux** [comment]
soft coded version ist done but here are some known bugs:
1. If you type a long messate by any input it gives you an `IndexError: list index out of range` error
2. Everything with bools don't quit work.

**Review by Jon-Kle — CHANGES_REQUESTED** [review]
## Good morning,

When I first looked at your code, it was hard to read because i did not immediately get how all these functions interact. Normally when I write code, i use internal functions very rarely.
But now I looked at it in more detail and i think you found a very elegant solution to the problem!

There are some minor things:
- When writing internal functions, the keyword `self` isn't necessary. It gets only used when defining methods that belong to a class.
- Internal functions in general have access to all variables defined in the function they're written in. The `global` keyword makes the variable visible in the whole script.
- If you want to define the type of an argument, you use `:` instead of `=`. But what i have seen, defining types in Python is not very common.
- Finally, in Python it is convention to use `snake_case`. For the command names in the CLI, i use `camelCase`, but only there.

About the bugs:
- the `bool()` casting of string doesn't work that well, so maybe just compare the input with `true, True, 1` and `false, False, 0` and then set the value to either `True` or `False`
- The `IndexError` appears, because the `numofoptions` includes the `back` and exit `options`, but maybe i am wrong. You could use `len(keyList)` instead of `numofoptions`.

**Comment by LeeLux** [comment]
@Jon-Kle I tried to not use `global` but it didn't work so I use it. Maybe someone else can figure out why. I removed `self` and got the `boolean` working.
The `IndexError` is still there because when I use `len(keyList)` as you suggested the `back` and `exit` numbers don't work anymore an I only use the numbers so we need a other way to fix it in the future.
At last I don't get the `snake_case` `camelCase` point of yours. Should I change something? The Methods names or the var names?

**Comment by Jon-Kle** [comment]
Nice! I will probably look into the problems you pointed out tomorrow. Or you can continue to search for a solution for the problem with the IndexError if you want, or you leave it to me. As you like.
With snake-case I ... essentially want you to change all the variable and function names, so the naming convention in the script stays the same.

**Review by Jon-Kle — APPROVED** [review]

**Pull request merged**
